server:
  port: 9999


spring:
  application:
    name: core

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

  mail:
    host: smtp.qq.com
    username: xxxxxxxxx
    password: xxxxxxxxx

    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  freemarker:
    content-type: text/html
    #后缀名
    suffix: .ftl
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true

    #freemarker配置



#设置一个邮件发送人
lance:
  mail:
    sender: 381016296@qq.com
